name: ✨ New Feature
description: Plan for a new feature
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature for the project! Please fill out the following information to help us understand your idea.

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Please provide a clear and concise description of the feature you would like to see added to the project.
      placeholder: It would be great if arctl could...
    validations:
      required: true

  - type: textarea
    id: plan
    attributes:
      label: Describe how to implement the feature
      description: Please provide a clear and concise description of how you would like to see the feature implemented.
      placeholder: The feature could be implemented by...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Describe any additional information
      description: Please provide any additional information that you think would be helpful if needed.
    validations:
      required: false

  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - nice to have
        - would make my life easier
        - i cannot use arctl without it
    validations:
      required: true
